import type { CommandHelpMeta } from "../lib/types.js"

export const HELP_BY_COMMAND: Record<string, CommandHelpMeta> = {
  auth: {
    command: "auth",
    summary: "Authentication commands for logging in, checking session state, and logging out.",
    usage: ["mindpocket auth <login|logout|status>"],
    arguments: [],
    options: [{ flags: "--help", description: "Show command help." }],
    authRequired: false,
    output: ["Use a concrete subcommand. Each subcommand returns its own JSON payload."],
    examples: ["mindpocket auth login", "mindpocket auth status", "mindpocket auth logout"],
    errors: ["VALIDATION_ERROR"],
  },
  "auth login": {
    command: "auth login",
    summary: "Start OAuth device authorization and store the resulting bearer token locally.",
    usage: ["mindpocket auth login [--server <url>]"],
    arguments: [],
    options: [
      {
        flags: "--server <url>",
        description: "Optional. Override the configured MindPocket server URL.",
      },
      { flags: "--help", description: "Show command help." },
    ],
    authRequired: false,
    output: ["Success JSON fields: ok, data.serverUrl, data.user, data.expiresAt."],
    examples: [
      "mindpocket auth login",
      "mindpocket auth login --server https://mindpocket.example.com",
    ],
    errors: ["SERVER_UNREACHABLE", "AUTH_TIMEOUT", "AUTH_DENIED", "VALIDATION_ERROR", "API_ERROR"],
  },
  "auth logout": {
    command: "auth logout",
    summary: "Remove the locally stored MindPocket CLI session.",
    usage: ["mindpocket auth logout"],
    arguments: [],
    options: [{ flags: "--help", description: "Show command help." }],
    authRequired: false,
    output: ["Success JSON fields: ok, data.loggedOut."],
    examples: ["mindpocket auth logout"],
    errors: ["INTERNAL_ERROR"],
  },
  "auth status": {
    command: "auth status",
    summary:
      "Report whether the current CLI session is authenticated and still valid on the server.",
    usage: ["mindpocket auth status"],
    arguments: [],
    options: [{ flags: "--help", description: "Show command help." }],
    authRequired: false,
    output: ["Success JSON fields: ok, data.authenticated, data.serverUrl, data.user."],
    examples: ["mindpocket auth status"],
    errors: ["SERVER_UNREACHABLE", "API_ERROR"],
  },
  config: {
    command: "config",
    summary: "Configuration commands for managing the target MindPocket server URL.",
    usage: ["mindpocket config <get|set server <url>>"],
    arguments: [],
    options: [{ flags: "--help", description: "Show command help." }],
    authRequired: false,
    output: ["Use a concrete subcommand. Each subcommand returns its own JSON payload."],
    examples: [
      "mindpocket config get",
      "mindpocket config set server https://mindpocket.example.com",
    ],
    errors: ["VALIDATION_ERROR"],
  },
  "config get": {
    command: "config get",
    summary: "Read the persisted CLI configuration.",
    usage: ["mindpocket config get"],
    arguments: [],
    options: [{ flags: "--help", description: "Show command help." }],
    authRequired: false,
    output: ["Success JSON fields: ok, data.serverUrl, data.configPath, data.hasSession."],
    examples: ["mindpocket config get"],
    errors: ["INTERNAL_ERROR"],
  },
  "config set server": {
    command: "config set server",
    summary: "Persist the MindPocket server URL used by future commands.",
    usage: ["mindpocket config set server <url>"],
    arguments: [{ name: "<url>", description: "Required. Target MindPocket base URL." }],
    options: [{ flags: "--help", description: "Show command help." }],
    authRequired: false,
    output: ["Success JSON fields: ok, data.serverUrl."],
    examples: ["mindpocket config set server https://mindpocket.example.com"],
    errors: ["VALIDATION_ERROR", "INTERNAL_ERROR"],
  },
  user: {
    command: "user",
    summary: "User profile commands for the authenticated MindPocket account.",
    usage: ["mindpocket user me"],
    arguments: [],
    options: [{ flags: "--help", description: "Show command help." }],
    authRequired: true,
    output: ["Use a concrete subcommand. Each subcommand returns its own JSON payload."],
    examples: ["mindpocket user me"],
    errors: ["AUTH_REQUIRED", "VALIDATION_ERROR"],
  },
  "user me": {
    command: "user me",
    summary: "Fetch the current authenticated user profile from the server.",
    usage: ["mindpocket user me"],
    arguments: [],
    options: [{ flags: "--help", description: "Show command help." }],
    authRequired: true,
    output: ["Success JSON fields: ok, data.id, data.email, data.name, data.avatar."],
    examples: ["mindpocket user me"],
    errors: ["AUTH_REQUIRED", "SERVER_UNREACHABLE", "API_ERROR"],
  },
  bookmarks: {
    command: "bookmarks",
    summary: "Bookmark commands for listing, reading, and creating bookmarks through MindPocket.",
    usage: [
      "mindpocket bookmarks list [--limit <n>] [--offset <n>] [--search <query>]",
      "mindpocket bookmarks get <id>",
      "mindpocket bookmarks create --url <url> [--title <title>] [--folder-id <id>]",
    ],
    arguments: [],
    options: [{ flags: "--help", description: "Show command help." }],
    authRequired: true,
    output: ["Use a concrete subcommand. Each subcommand returns its own JSON payload."],
    examples: ["mindpocket bookmarks list", "mindpocket bookmarks get bk_123"],
    errors: ["AUTH_REQUIRED", "VALIDATION_ERROR"],
  },
  "bookmarks list": {
    command: "bookmarks list",
    summary: "List bookmarks visible to the current user.",
    usage: [
      "mindpocket bookmarks list [--limit <n>] [--offset <n>] [--search <query>] [--folder-id <id>] [--type <type>] [--platform <platform>]",
    ],
    arguments: [],
    options: [
      { flags: "--limit <n>", description: "Optional. Page size. Default 20." },
      { flags: "--offset <n>", description: "Optional. Pagination offset. Default 0." },
      { flags: "--search <query>", description: "Optional. Keyword search." },
      { flags: "--folder-id <id>", description: "Optional. Filter by folder ID." },
      { flags: "--type <type>", description: "Optional. Filter by bookmark type." },
      { flags: "--platform <platform>", description: "Optional. Filter by source platform." },
      { flags: "--help", description: "Show command help." },
    ],
    authRequired: true,
    output: ["Success JSON fields: ok, data.bookmarks, data.total, data.hasMore."],
    examples: ["mindpocket bookmarks list", "mindpocket bookmarks list --search AI --limit 10"],
    errors: ["AUTH_REQUIRED", "VALIDATION_ERROR", "SERVER_UNREACHABLE", "API_ERROR"],
  },
  "bookmarks get": {
    command: "bookmarks get",
    summary: "Fetch a single bookmark and its tags by bookmark ID.",
    usage: ["mindpocket bookmarks get <id>"],
    arguments: [{ name: "<id>", description: "Required. Bookmark ID." }],
    options: [{ flags: "--help", description: "Show command help." }],
    authRequired: true,
    output: ["Success JSON fields: ok, data.id, data.title, data.url, data.tags."],
    examples: ["mindpocket bookmarks get bk_123"],
    errors: ["AUTH_REQUIRED", "API_ERROR", "SERVER_UNREACHABLE"],
  },
  "bookmarks create": {
    command: "bookmarks create",
    summary: "Create a bookmark by sending a URL through the MindPocket ingest pipeline.",
    usage: ["mindpocket bookmarks create --url <url> [--title <title>] [--folder-id <id>]"],
    arguments: [],
    options: [
      { flags: "--url <url>", description: "Required. Bookmark URL to ingest." },
      { flags: "--title <title>", description: "Optional. Override the detected title." },
      { flags: "--folder-id <id>", description: "Optional. Save into a specific folder." },
      { flags: "--help", description: "Show command help." },
    ],
    authRequired: true,
    output: ["Success JSON fields: ok, data.bookmarkId, data.title, data.type, data.status."],
    examples: [
      "mindpocket bookmarks create --url https://example.com",
      "mindpocket bookmarks create --url https://example.com --title Example",
    ],
    errors: ["AUTH_REQUIRED", "VALIDATION_ERROR", "SERVER_UNREACHABLE", "API_ERROR"],
  },
  folders: {
    command: "folders",
    summary: "Folder commands for listing bookmark folders visible to the authenticated user.",
    usage: ["mindpocket folders list"],
    arguments: [],
    options: [{ flags: "--help", description: "Show command help." }],
    authRequired: true,
    output: ["Use a concrete subcommand. Each subcommand returns its own JSON payload."],
    examples: ["mindpocket folders list"],
    errors: ["AUTH_REQUIRED", "VALIDATION_ERROR"],
  },
  "folders list": {
    command: "folders list",
    summary:
      "List folders for the authenticated user, including a small bookmark preview in each folder.",
    usage: ["mindpocket folders list"],
    arguments: [],
    options: [{ flags: "--help", description: "Show command help." }],
    authRequired: true,
    output: [
      "Success JSON fields: ok, data.folders[].id, data.folders[].name, data.folders[].items.",
    ],
    examples: ["mindpocket folders list"],
    errors: ["AUTH_REQUIRED", "SERVER_UNREACHABLE", "API_ERROR"],
  },
}
